Update the README
kadena-io/chainweb-data pull request #130
Opened 2023-01-20 19:39 UTC by enobayram

2023-01-20 22:50 UTC, emmanueldenloye requested changes

2023-01-20 22:50 UTC, emmanueldenloye commented on README.org
> +~chainweb-data~'s all search endpoints (~/txs/{events,search,account}~) support a common workflow
This should read 
```
All of ~chainweb-data~'s search endpoints
```

2023-01-20 22:50 UTC, emmanueldenloye commented on README.org
> +and upper bound on the amount of time the server will spend for searching results. Normally, the
This should read
```
an upper bound
```

2023-01-20 23:54 UTC, enobayram commented
@emmanueldenloye thanks for catching those I've fixed them now.

2023-01-21 00:11 UTC, emmanueldenloye approved these changes

2023-01-23 13:15 UTC, merged