Fill command diagnostics
kadena-io/chainweb-data pull request #151
Opened 2023-06-07 22:43 UTC by emmanueldenloye

2023-07-14 13:52 UTC, enobayram requested changes
Great job diagnosing and fixing this bug, which has been a source of inconvenience for `chainweb-data` operators.

2023-07-14 13:52 UTC, enobayram commented on haskell-src/lib/ChainwebData/Env.hs
> +  , _fillArgs_fillErrorLog :: Maybe FilePath
Do we still need this argument now that we have fixed the issue? If we're planning to keep it, we need to have a good explanation of what this log file means. I.e. which kinds of errors are logged here.

2023-07-14 13:52 UTC, enobayram commented on haskell-src/lib/ChainwebData/Env.hs
> +logFile message = optional $ strOption (long message <> metavar "LOG_FILE" <> help "File to log to")
```suggestion
fillErrorLogFile :: Parser (Maybe FilePath)
fillErrorLogFile = optional $ strOption (long "fill-error-log-file" <> metavar "PATH" <> help "File to write ??? kind of logs")
```
Is there any reason to receive the `long` name as an argument here?

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Worker.hs
> +
```suggestion
batchWrites :: 
  P.Pool Connection -> 
  (ChainId, Int, Int) -> 
  Maybe FilePath -> 
  [Block] -> 
  [[T.Text]] -> 
  [[Transaction]] -> 
  [[Event]] -> 
  [[Signer]] -> 
  [[Transfer]] -> 
  IO ()
batchWrites pool _chunkRange errorLogFile bs kss tss ess sss tfs = 
  P.withResource pool $ \c -> withTransaction c $ do

```

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Server.hs
> +      gaps env (FillArgs fillDelay Nothing) -- TODO: This shouldn't be Nothing
Let's deal with this TODO one way or another

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Gaps.hs
> +              , connectDatabase = "chainweb-data"
This doesn't look good

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Gaps.hs
> +              pure $ Right []
I see a lot of code duplication of this kind, would be nice to deduplicate them (if we're planning to keep the errorLogFile)

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Worker.hs
> +        S.logg Debug $ fromString $ printf "Blocks inserted: %d" $ length bs
```suggestion
      let 
        logInsertStats entityName inserted attempted = 
          forM_ errorLogFile $ \fp -> withFileLogger fp Debug $ do
            S.logg Debug $ "Over range: " <> fromString (show _chunkRange)
            S.logg Debug $ fromString $ printf "%s inserted: %s" entityName (show inserted)
            S.logg Debug $ fromString $ printf "%s attempted: %d" entityName attempted
      logInsertStats "Blocks" blocksReturned (length bs)
```

Seems like we can reuse this function for all the other cases

2023-07-14 13:52 UTC, enobayram commented on haskell-src/exec/Chainweb/Worker.hs
> +              batchWrites pool chunkRange (appendChain chain <$> errorLogFile) (M.elems bs) (M.elems kss) (M.elems tss) (M.elems ess) (M.elems sss) (M.elems tfs)
```suggestion
              batchWrites pool chunkRange (appendChain chain <$> errorLogFile) (M.elems bs) 
                (M.elems kss) (M.elems tss) (M.elems ess) (M.elems sss) (M.elems tfs)
```

2023-07-15 04:13 UTC, emmanueldenloye commented on haskell-src/exec/Chainweb/Gaps.hs
> +              , connectDatabase = "chainweb-data"
I've taken this info out.

2023-07-18 16:24 UTC, enobayram approved these changes
LGTM! Great work with the fixes!

2023-07-18 16:24 UTC, enobayram commented on haskell-src/exec/Chainweb/Server.hs
> +      gaps env (FillArgs fillDelay) -- TODO: This shouldn't be Nothing
```suggestion
      gaps env (FillArgs fillDelay)
```

2023-07-18 16:24 UTC, enobayram commented on haskell-src/exec/Chainweb/Worker.hs
> +                (M.elems kss) (M.elems tss) (M.elems ess) (M.elems sss) (M.elems tfs)
```suggestion
              batchWrites pool (M.elems bs) (M.elems kss) (M.elems tss) (M.elems ess) (M.elems sss) (M.elems tfs)
```
No need to introduce a whitespace diff

2023-07-18 16:24 UTC, enobayram commented on haskell-src/exec/Chainweb/Worker.hs
> +              logger Error $ fromString $ show e
```suggestion
          logger Error $ fromString $ printf "Couldn't fetch payload batch for chain: %d" (unChainId chain)
          logger Error $ fromString $ show e
```

2023-07-18 18:39 UTC, merged