Richlist
kadena-io/chainweb-data pull request #39
Opened 2020-09-10 21:32 UTC by emilypi

This PR adds a command for the user to construct a richlist given sync'd node data tables. The command looks like this: 

```bash
> cabal exec chainweb-data -- richlist --db-path=~/.local/share
```

Which copies the sqlite data files to the current working directory, runs a script on them via `sqlite3` to consolidate the data into a richlist, and outputs a `richlist.csv`, doing cleanup along the way. It's recommended that the user run this as a cronjob at regular intervals. Keep in mind that this requires a node that has synced at some point is required for this to work. It will be made more robust in later iterations (perhaps calling `backfill` first in order to sync the data.

2020-09-17 18:29 UTC, mightybyte requested changes

2020-09-17 18:30 UTC, mightybyte commented
Also need to get the tests passing.

2020-09-17 18:32 UTC, emilypi commented on exec/Main.hs
> +      fp' <- case fp == "" of
Yeah, we can do that.

2020-09-30 02:41 UTC, emilypi commented on exec/Chainweb/RichList.hs
> +      True -> for_ [0::Int .. 19] $ \i -> do
Now parses the existing sqlite tables to establish # of chains

2021-02-01 08:07 UTC, merged